// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package gensql

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const addUsersToTeam = `-- name: AddUsersToTeam :batchexec
insert into users_to_teams (user_id, team_name) 
values ($1, $2) 
on conflict (user_id, team_name) do nothing
`

type AddUsersToTeamBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type AddUsersToTeamParams struct {
	UserID   string
	TeamName string
}

func (q *Queries) AddUsersToTeam(ctx context.Context, arg []AddUsersToTeamParams) *AddUsersToTeamBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.TeamName,
		}
		batch.Queue(addUsersToTeam, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &AddUsersToTeamBatchResults{br, len(arg), false}
}

func (b *AddUsersToTeamBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *AddUsersToTeamBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const ensureUsers = `-- name: EnsureUsers :batchexec
insert into users (user_id, user_name, is_active) 
values ($1, $2, $3) 
on conflict (user_id) do update
set user_name = excluded.user_name,
    is_active = excluded.is_active
`

type EnsureUsersBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type EnsureUsersParams struct {
	UserID   string
	UserName string
	IsActive bool
}

func (q *Queries) EnsureUsers(ctx context.Context, arg []EnsureUsersParams) *EnsureUsersBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.UserName,
			a.IsActive,
		}
		batch.Queue(ensureUsers, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &EnsureUsersBatchResults{br, len(arg), false}
}

func (b *EnsureUsersBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *EnsureUsersBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
